name: eip55
description: Utility to convert an upper or lowercase Web3/Ethereum address to a checksum address (EIP55).
version: 1.0.0
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_eip55

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pointycastle: ^3.4.0

dev_dependencies:
  test: ^1.20.0
  lints: ^1.0.0
